name: Deploy PHP App to Azure Web App

on:
  push:
    branches:
      - master  # <-- Ini disesuaikan dengan branch kamu sekarang

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: hawa-first-app
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
